<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ABRF4IV4" failures="3" tests="4" name="Find new car Test" time="25.36" errors="0" timestamp="2021-05-17T23:40:16 IST">
  <testcase classname="testcases.FindCarTest" name="findCarTest" time="8.73">
    <failure type="java.lang.AssertionError" message="failed intentionally">
      <![CDATA[java.lang.AssertionError: failed intentionally
at testcases.FindCarTest.findCarTest(FindCarTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- findCarTest -->
  <testcase classname="testcases.FindCarTest" name="findCarTest" time="0.002">
    <skipped/>
  </testcase> <!-- findCarTest -->
  <testcase classname="testcases.FindCarTest" name="findCarTest" time="5.238">
    <failure type="java.lang.AssertionError" message="failed intentionally">
      <![CDATA[java.lang.AssertionError: failed intentionally
at testcases.FindCarTest.findCarTest(FindCarTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- findCarTest -->
  <testcase classname="testcases.FindCarTest" name="findCarTest" time="8.586">
    <failure type="java.lang.AssertionError" message="failed intentionally">
      <![CDATA[java.lang.AssertionError: failed intentionally
at testcases.FindCarTest.findCarTest(FindCarTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- findCarTest -->
</testsuite> <!-- Find new car Test -->
